### ISSUE TITLE
Effet de bord des tests. La mémoire du serveur n'est pas vidée

### ISSUE THREAD

**Issue by wfortin** [glo-ulaval/Architecture#1]
Voir moi ou @jrochette pour plus d'info.
À vérifier...

**Comment by bgagnonadam** [comment]
Serait-ce possible d'avoir un petit peu plus d'information? 
Merci.

**Comment by jrochette** [comment]
Il y a des problemes de mémoire quand on run les test il y a des cours "vide" ou des offres. On vous explique ça lundi.

**Comment by bgagnonadam** [comment]
Résolu.
