### ISSUE TITLE
Build failure lors d'un "mvn clean test"

### ISSUE THREAD

**Issue by bgagnonadam** [glo-ulaval/Architecture#6]
Salut, aujourd'hui on a modifié du code dans la partie des disponibilitées mais en voulant voir les test par maven, on a eu trois tests qui n'ont pas passés : 

Failed tests:   canDeleteASchedule(cours.ulaval.glo4003.persistence.XMLScheduleRepositoryTest): expected:<0> but was:<1>
 canFindAll(cours.ulaval.glo4003.persistence.XMLScheduleRepositoryTest): expected:<10> but was:<11>
 cannotStoreADuplicateSchedule(cours.ulaval.glo4003.persistence.XMLScheduleRepositoryTest): expected:<1> but was:<2>

Tests run: 105, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Pouvez vous regarder ca?

Merci 

Bruno

**Comment by vseguin** [comment]
Fixed.
