### ISSUE TITLE
Clean up du ScheduleController

### ISSUE THREAD

**Issue by jrochette** [glo-ulaval/Architecture#8]
ScheduleController is a f******\* mess. Nuf' said

**Comment by bgagnonadam** [comment]
Allo,
Un des problèmes est que si nous créons un horaire sans y ajouter une section de cours et que nous faisons générer, nous allons arriver à un horaire qui est vide. Il ne faudrait pas qu'un horaire vide soit persisté.

**Comment by bgagnonadam** [comment]
La boite de recherche ne devrait pas être dans la page de menu, idéalement elle serait présente dans la page visualiser offre de cours, créer un horaire.
